# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "llvm-msvc-test-stosb"

[target.test]
type = "executable"
sources = ["src/main.cpp"]
compile-features = ["cxx_std_20"]
compile-options = ["-fauto-generate-ir"]
